### ISSUE TITLE
Export Device Types from NetBox

### ISSUE THREAD

**Issue by bortok** [netreplica/nrx#109]
Export Device Types from NetBox and map them to Containerlab node types. This would allow to emulate different device models of the same platform. On Containerlab side this is supported by SR Linux

**Comment by tardoe** [comment]
Use-case: Be able to map between DeviceTypes and Containerlab kinds.
E.g. 
- Netbox DeviceType Slug of `7220-ixr-d3l` could map to `ixrd3l` which is the string needed to represent this type as a Containerlab `kind` against the SR-Linux container image.
```
nodes:
       syd1-pd1-sp1:
            kind: srl
            type: ixrd3l <----------------------------------- type mapped from DeviceType.
            image: ghcr.io/nokia/srlinux:latest
```
- Netbox device types MX104, MX204, MX480, MX960 all map to the `juniper_vmx ` kind in Containerlab. 
```
nodes:
       syd1-edge1:
            kind: juniper_vmx <------- actually an MX204 in Netbox, only vMX is emulatable.
            image: vmx:23.1R10 <-------|
```
